import { z } from 'zod';

export const App_url = {
  maxWidth: '302px',
  DELAY: {
    ENQUIRY_POPUP_DELAY: 30000,
  },
  CURRENCY: '₹',
  image: {
    HERO_IMAGE: '/assets/icon/hero.webp',
    SERVICE_BANNER: '/assets/icon/service-banner.webp',
    MOBILE_APP: '/assets/icon/iphone.webp',
    BLOG_IMG: '/assets/icon/blogimg.png',
    SIGNIN_IMG: '/assets/icon/sign_in_back.png',
    SIGN_UP_IMG: '/assets/icon/sign_up_back.png',
    CONTACT_HERO: '/assets/icon/contacthero.webp',
    PACKAGES_HERO: '/assets/icon/package-gero.webp',
    SERVICES_BG: '/assets/icon/servicebg.png',
    ANKUSH_IMG: '/assets/icon/ankush.webp',
    BOOK_APPOINTMENT: '/assets/icon/bookappoitment.png',
    EXPERT_WEBINAR: '/assets/icon/neet-banner.jpg',
    BIO: '/assets/icon/bio.jpg',
    PHYSIC: '/assets/icon/physic.jpg',
    MENTOR: '/assets/icon/mentor.png',
    CLASS_ROOM: '/assets/icon/classroom.png',
    EXPERT_BADGE: '/assets/icon/expert.png',
    WEBINAR_PLACEHOLDER: '/assets/icon/webinarplaceholder.png',
  },
  icon: {
    ANNOUNCEMENTSTAR: '/assets/icon/anouncementstar.svg',
    LOGO: '/assets/icon/logo.svg',
    CALENDER: '/assets/icon/calendar.svg',
    CALENDER_ACTIVE: '/assets/icon/calender-active.svg',
    SIGNIN: '/assets/icon/sign-in.svg',
    FOOTER_LOGO: '/assets/icon/footer_logo.svg',
    INSTAGRAM: '/assets/icon/instagram.svg',
    YOUTUBE: '/assets/icon/youtube.svg',
    LINKEDIN: '/assets/icon/LinkedIn.svg',
    LIGHT: '/assets/icon/light.svg',
    EARTH_HAND: '/assets/icon/earth-hand.svg',
    TARGET: '/assets/icon/target.svg',
    HEADPHONE: '/assets/icon/headfone.svg',
    BUILDING: '/assets/icon/building.svg',
    EDUCATION: '/assets/icon/edu.svg',
    IDEA: '/assets/icon/idea.svg',
    FILE: '/assets/icon/file.svg',
    BLOG_CALENDER: '/assets/icon/blog-calender.svg',
    BLOG_ARROW: '/assets/icon/blog-arrow.svg',
    ARROW_RIGHT: '/assets/icon/ArrowRight.svg',
    STAR: '/assets/icon/star.svg',
    FAQ_IMG: '/assets/icon/faq.webp',
    DOWN_ARROW: '/assets/icon/downArrow.svg',
    ZOOM_LOGO: '/assets/icon/zoom.svg',
    WEB_ADMIN: '/assets/icon/webadmin.png',
    WEBINAR_BG: '/assets/icon/webinarbg.png',
    WEB_CALENDER: '/assets/icon/web-calender.svg',
    WEB_CLOCK: '/assets/icon/web-clock.svg',
    SEARCH: '/assets/icon/inquary.svg',
    SPARKLE: '/assets/icon/Sparkle.svg',
    SIGN_IN: '/assets/icon/signin.png',
    MOBILE: '/assets/icon/mobile.svg',
    CONTACT_HERO: '/assets/icon/contacthero.png',
    USER: '/assets/icon/User.svg',
    EMAIL_ICON: '/assets/icon/email.svg',
    CHAT: '/assets/icon/chat.svg',
    PHONE: '/assets/icon/device.svg',
    ADDRESS: '/assets/icon/Buildings.svg',
    CALL: '/assets/icon/call.svg',
    EMAIL_THEME: '/assets/icon/emailtheam.svg',
    ABOUT_IMG: '/assets/icon/aboutimage.png',
    ABOUT_BG_IMG: '/assets/icon/aboutbg.webp',
    ABOUT_HERO_IMG: './assets/icon/',
    MISSION: '/assets/icon/mission.png',
    VISION: '/assets/icon/vision.png',
    COURSE: '/assets/icon/GraduationCap.svg',
    AI_ICON: '/assets/icon/AI_icons.png',
    B1: '/assets/icon/b1.svg',
    B2: '/assets/icon/b2.svg',
    B3: '/assets/icon/b3.svg',
    B4: '/assets/icon/b4.png',
    B5: '/assets/icon/b5.png',
    EARTH: '/assets/icon/earth.svg',
    SUCCESS_GIF: '/assets/icon/sucessfullyicon.gif',
    COLLAGE_ICON: '/assets/icon/College.png',
    ADMINSSION_ICON: '/assets/icon/Admission-Insight.png',
    EXPLORER_ICON: '/assets/icon/College-Explorer.png',
    CAREER_ICON: '/assets/icon/Career-Guidance.png',
    FEACHER_ICON: '/assets/icon/features_icons.png',
    NOTE_ICON: '/assets/icon/note-icons.png',
    PROFILE_ICON: '/assets/icon/myprofile.svg',
    PROFILE_MAIN_ICON: '/assets/icon/profile_main.svg',
    ALERT_ICON: '/assets/icon/triangle-alert.svg',
    FALLBACK_PROFILE: '/assets/icon/fallbackprofile.jpg',
    WEBINAR_DUMMY: '/assets/icon/webinar_dummy.jpeg',
    CAM: '/assets/icon/cam.svg',
    FAVICON: '/assets/favicon.ico',
    FOLDER: '/assets/icon/folder.svg',
    PDF: '/assets/icon/pdf.svg',
    URL: '/assets/icon/link.svg',
    FOLDER_ARROW: '/assets/icon/arrowfolder.svg',
    ROBOT_CUTOFF: '/assets/icon/robot-cutoff.svg',
    ROBOT_PREDICT: '/assets/icon/robot-predict.svg',
    ANALYTICS: '/assets/icon/analysis.svg',
    TEN_ICON: '/assets/icon/ten.png',
    DOMICILE_ICON: '/assets/icon/domicile.svg',
    INCOME_ICON: '/assets/icon/income.svg',
    CAST_ICON: '/assets/icon/cast.svg',
    GREEN_TICK: '/assets/icon/greentick.svg',
    REUPLOAD: '/assets/icon/reupload.svg',
    TRASH: '/assets/icon/trash.svg',
    EYE: '/assets/icon/eye.svg',
    YELLOW_INFO: '/assets/icon/Info.svg',
    VERIFIED: '/assets/icon/verified.png',
    NOT_VERIFIED: '/assets/icon/delete.png',
    ACCURATE: '/assets/icon/accurate.svg',
    TREND: '/assets/icon/trend.svg',
    COLLAGE_PR: '/assets/icon/collage.svg',
    PERSON: '/assets/icon/person.svg',
    CATEGORY_CAP: '/assets/icon/categorycap.svg',
    AI_VERIFY: '/assets/icon/Aiv.svg',
    INSTANT_RESULT: '/assets/icon/instant.svg',
    SECURE_PROCESS: '/assets/icon/secure.svg',
    PDF_SUPPORT: '/assets/icon/pdfIcon.svg',
    JPG_SUPPORT: '/assets/icon/jpg.svg',
    PNG_SUPPORT: '/assets/icon/png.svg',
    USER_CIRCLE: '/assets/icon/UserCircle.svg',
    EDIT_PENCIL: '/assets/icon/PencilSimpleLine.svg',
    PENDING_ICON: '/assets/icon/pending.png',
    AI_PROFILE_PROCESSING: '/assets/icon/analisys-profile.svg',
    AI_DOC_PROCESSING: '/assets/icon/robot.svg',
    AI_STEP1: '/assets/icon/step1.svg',
    AI_STEP1O: '/assets/icon/step1o.svg',
    AI_STEP1P: '/assets/icon/step1p.svg',
    AI_STEP2C: '/assets/icon/compleated-ai.svg',
    AI_STEP2O: '/assets/icon/ongoing-ai.svg',
    AI_STEP2P: '/assets/icon/pending-ai.svg',
    AI_STEP3C: '/assets/icon/3compleated-ai.svg',
    AI_STEP3O: '/assets/icon/3ongoing-ai.svg',
    AI_STEP3P: '/assets/icon/3pending-ai.svg',
    AI_STEP4C: '/assets/icon/4compleated-ai.svg',
    AI_STEP4O: '/assets/icon/4ongoing-ai.svg',
    AI_STEP4P: '/assets/icon/4pending-ai.svg',
    AI_STEP5C: '/assets/icon/5compleatedC.svg',
    AI_STEP5O: '/assets/icon/5ongoing.svg',
    AI_STEP5P: '/assets/icon/5pending.svg',
    DOC_VALID: '/assets/icon/valid.svg',
    DOC_CALENDER: '/assets/icon/calender.svg',
    DOC_SHIELD: '/assets/icon/ShieldCheck.svg',
    DOC_USER: '/assets/icon/docuser.svg',
    DOC_FILE: '/assets/icon/FileText.svg',
    DOC_APPROVED: '/assets/icon/approved.svg',
    EXAM_DETAIL: '/assets/icon/GraduationCap2.svg',
    SCORE_DETAIL: '/assets/icon/Trophy.svg',
    PREFERENCES: '/assets/icon/UserCircle.svg',
    DEMO: '/assets/icon/demo.png',
    VALID_DOC: '/assets/icon/validoc.svg',
    CALENDER_CON: '/assets/icon/cal.svg',
    VIDEO_CON: '/assets/icon/video.svg',
    CALENDER_DATE: '/assets/icon/calender-date.svg',
    ARROW_RIGHT_CAL: '/assets/icon/arrow-right.svg',
    ARROW_LEFT_CAL: '/assets/icon/arrow-left.svg',
    CLOCK_SHCEDULE: '/assets/icon/clock.svg',
    VIDEO_CAM: '/assets/icon/VideoCamera.svg',
    MAP: '/assets/icon/map.svg',
    CALL_POPUP: '/assets/icon/PhoneCall.svg',
    CLIPBOARD: '/assets/icon/clipboard.svg',
    BOOKLET_FOLDER: '/assets/icon/folderBooklet.svg',
    BOOKLET_PDF: '/assets/icon/pdfbooklet.svg',
    BOOKLET_REPORT: '/assets/icon/report.svg',
    DATE_FIELD: '/assets/icon/date.svg',
    UPLOAD_ICON: '/assets/icon/upload-here.svg',
    CALL_ICON: '/assets/icon/callPhone.svg',
    SUCCESS_GIF2: '/assets/icon/success.gif',

    // Dummy
    DUMMY_10: '/assets/dummy/10.pdf',
    DUMMY_12: '/assets/dummy/12.png',
    DUMMY_DOMICILE: '/assets/dummy/domicile.png',
    DUMMY_LC: '/assets/dummy/lc.png',
  },
  link: {
    HOME_URL: '/',
    ABOUT_URL: '/about',
    SIGNIN_URL: '/signin',
    SIGNUP_URL: '/signup',
    DASHBOARD_URL: '/dashboard',
  },
  ApiEndPoint: {},
  AcceptType: {
    VERIFY_ACCEPT_FORMAT_IMAGE: ['jpg', 'jpeg', 'png'],
    IMAGE_INPUT: '.jpg,.jpeg,.png',
  },
};

export const NAV_CONFIG = {
  external: [
    { name: 'Home', href: App_url.link.HOME_URL },
    { name: 'About', href: App_url.link.ABOUT_URL },
  ],
  topper: [
    { name: 'Home', href: App_url.link.HOME_URL },
    { name: 'About', href: App_url.link.ABOUT_URL },
  ],
};

export const ROLES = {
  USER: 'user',
  TOPPER: 'topper',
};
